[technote]
id = "DMTN-285"
series_id = "DMTN"
canonical_url = "https://dmtn-285.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-285"
github_default_branch = "main"
date_created = 2024-03-06T01:48:57Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Gregory P."
name.family = "Dubois-Felsmann"
internal_id = "duboisfelsmanngp"
orcid = "https://orcid.org/0000-0003-1598-6979"
[[technote.authors.affiliations]]
name = "IPAC"
internal_id = "IPAC"
address = "California Institute of Technology, MS 100-22, Pasadena, CA 91125, USA"
